services:
  postgres:
    container_name: interapp-postgres
    image: postgres:16-alpine
    restart: always
    ports:
      - 5432:5432
    command: postgres
    env_file:
      - ./interapp-backend/.env.production
    volumes:
      - ./interapp-backend/pgdata:/var/lib/postgresql/data
    networks:
      - interapp-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 60s

  redis:
    container_name: interapp-redis
    image: redis:alpine
    restart: always
    env_file:
      - ./interapp-backend/.env.production
    ports:
      - 6379:6379
    networks:
      - interapp-network
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 2s
      timeout: 2s
      retries: 7

  scheduler:
    container_name: interapp-scheduler
    restart: on-failure
    build:
      context: ./interapp-backend
      dockerfile: scheduler/prod.Dockerfile
    env_file:
      - ./interapp-backend/.env.production
    networks:
      - interapp-network
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
        - ./dump:/tmp/dump
        - ./minio-dump:/tmp/minio-dump

  minio:
    container_name: interapp-minio
    image: minio/minio
    restart: on-failure
    command: minio server /data
    env_file:
      - ./interapp-backend/.env.production
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - ./interapp-backend/minio_data:/data
    networks:
      - interapp-network
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 2s
      timeout: 2s
      retries: 5
      start_period: 60s
    depends_on:
      postgres:
        condition: service_healthy


  backend:
    container_name: interapp-backend
    restart: always
    build:
      context: ./interapp-backend
      dockerfile: prod.Dockerfile
    env_file:
      - ./interapp-backend/.env.production
    environment:
      - APP_VERSION=${APP_VERSION}
    ports:
      - 8000:8000
    networks:
      - interapp-network
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  frontend:
    container_name: interapp-frontend
    build:
      context: ./interapp-frontend
      dockerfile: prod.Dockerfile
    ports:
      - 3000:3000
    env_file:
      - ./interapp-frontend/.env.production
    environment:
      - NEXT_PUBLIC_APP_VERSION=${APP_VERSION}
    networks:
      - interapp-network
    depends_on:
      - backend
      - postgres
  
  nginx:
    container_name: interapp-nginx
    build:
      context: ./nginx
      dockerfile: prod.Dockerfile
    restart: always
    ports:
      - 80:80
    networks:
      - interapp-network
    depends_on:
      - frontend

networks:
  interapp-network:
    driver: bridge
