version: '3'

services:
  postgres:
    container_name: interapp-postgres
    image: postgres:alpine
    restart: on-failure
    ports:
      - 5432:5432
    command: postgres 
    env_file:
      - ./interapp-backend/.env
    networks:
      - interapp-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    container_name: interapp-backend
    restart: on-failure
    build: 
      context: ./interapp-backend
      dockerfile: Dockerfile
    develop:
      watch:
        - path: ./interapp-backend/api
          action: sync
          target: /app/api
    env_file:
      - ./interapp-backend/.env
    environment:
      - POSTGRES_HOST=interapp-postgres
      - POSTGRES_PORT=5432
      - API_PORT=8000
    ports:
      - 8000:8000
    networks:
      - interapp-network
    depends_on:
      postgres:
        condition: service_healthy
    
  frontend:
    container_name: interapp-frontend
    build: 
      context: ./interapp-frontend
      dockerfile: Dockerfile
    volumes:
      - ./interapp-frontend/src:/app/src
    ports:
      - 3000:3000
    networks:
      - interapp-network
    depends_on:
      - backend
      - postgres

networks:
  interapp-network:
    driver: bridge
