version: "3"

services:
  postgres:
    container_name: interapp-postgres
    image: postgres:alpine
    restart: on-failure
    ports:
      - 5432:5432
    command: postgres
    env_file:
      - ./interapp-backend/.env.development
    volumes:
      - ./interapp-backend/pgdata:/var/lib/postgresql/data
    networks:
      - interapp-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 2s
      retries: 5
      start_period: 60s
    deploy:
      resources:
        reservations:
          cpus: '0.5'
          memory: 2G
  
  redis:
    container_name: interapp-redis
    image: redis:alpine
    restart: on-failure
    env_file:
      - ./interapp-backend/.env.development
    ports:
      - 6379:6379
    networks:
      - interapp-network
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 2s
      timeout: 2s
      retries: 7

  scheduler:
    container_name: interapp-scheduler
    restart: on-failure
    build:
      context: ./interapp-backend
      dockerfile: scheduler/dev.Dockerfile
    develop:
      watch:
        - path: ./interapp-backend/scheduler
          action: sync
          target: /app/scheduler
    env_file:
      - ./interapp-backend/.env.development
    networks:
      - interapp-network
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  minio:
    container_name: interapp-minio
    image: minio/minio
    restart: on-failure
    command: minio server /data
    env_file:
      - ./interapp-backend/.env.development
      - ./interapp-backend/.env.local
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - ./interapp-backend/minio_data:/data
    networks:
      - interapp-network
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 2s
      timeout: 2s
      retries: 5
      start_period: 60s
    depends_on:
      postgres:
        condition: service_healthy

    

  backend:
    container_name: interapp-backend
    restart: on-failure
    build:
      context: ./interapp-backend
      dockerfile: dev.Dockerfile
    develop:
      watch:
        - path: ./interapp-backend/api
          action: sync
          target: /app/api
        - path: ./interapp-backend/db
          action: sync
          target: /app/db
    env_file:
      - ./interapp-backend/.env.development
    ports:
      - 8000:8000
    networks:
      - interapp-network
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      minio:
        condition: service_healthy

  frontend:
    container_name: interapp-frontend
    build:
      context: ./interapp-frontend
      dockerfile: dev.Dockerfile
    volumes:
      - ./interapp-frontend/src:/app/src
    env_file:
      - ./interapp-frontend/.env.development
    ports:
      - 3000:3000
    networks:
      - interapp-network
    depends_on:
      - backend
    deploy:
      resources:
        reservations:
          cpus: '0.5'
          memory: 3G
        

networks:
  interapp-network:
    driver: bridge
