name: Pipeline

on:
  push:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  test-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build test environment
        run: docker compose -f docker-compose.test.yml build --no-cache

      - name: Run test environment
        run: docker compose -f docker-compose.test.yml up -d

      - name: Setup bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      
      - name: Install dependencies
        run: cd interapp-backend && bun install
      - name: Test with bun
        run: cd interapp-backend && bun run test

      - name: Tear down test environment
        run: docker compose -f docker-compose.test.yml down
  
