name: Pipeline

on:
  push:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  test-backend:
    name: Test backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build test environment
        run: docker compose -f docker-compose.test.yml build --no-cache

      - name: Run test environment
        run: docker compose -f docker-compose.test.yml up -d

      - name: Setup bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.1.3
      
      - name: Install dependencies
        run: cd interapp-backend && bun install

      - name: Lint code
        run: cd interapp-backend && bun run lint
      
      - name: Run unit and api tests
        run: cd interapp-backend && bun run test

      - name: Tear down test environment
        run: docker compose -f docker-compose.test.yml down
  
  build-application:
    name: Build application
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup prod environment
        run: docker compose -f docker-compose.prod.yml up -d --build

      - name: Tear down prod environment
        run: docker compose -f docker-compose.prod.yml down
